_pages/developer-engagement/webcompat-sprint.md

Fixes 
- correct link to discourse
- correct links for bug triager and outreacher

correction for links

---

_pages/developer-engagement/webcompat-sprint.md

this will fix https://github.com/mozilla/activate.mozilla.community/issues/24 if proposal accepted

correcting the disocurse link

---

_data/l10n/fr.yml
_data/l10n/pt.yml
_pages/es/faq.md
_pages/fr/developer-engagement.md
_pages/fr/developer-engagement/rust-hack.md
_pages/fr/developer-engagement/webcompat-sprint.md
_pages/fr/experiments.md
_pages/fr/experiments/test-pilot.md
_pages/fr/faq.md
_pages/fr/index.md
_pages/fr/participation.md
_pages/fr/roadmap.md
_pages/pt/developer-engagement.md
_pages/pt/developer-engagement/rust-hack.md
_pages/pt/developer-engagement/webcompat-sprint.md
_pages/pt/experiments.md
_pages/pt/experiments/test-pilot.md
_pages/pt/faq.md
_pages/pt/index.md
_pages/pt/participation.md
_pages/pt/roadmap.md
_sass/_layout.scss

Thanks to @comzeradd that solve my problems with git

Adding language template and pt and fr

---

_data/l10n/pt.yml
_pages/pt/developer-engagement.md
_pages/pt/developer-engagement/rust-hack.md
_pages/pt/experiments.md
_pages/pt/experiments/test-pilot.md
_pages/pt/index.md
_pages/pt/roadmap.md

Hi, i did a review and found erros and pages untranslated.

Review and Translated Articles to PT

---

_layouts/page.html

URLfying params to fix the links.
Fixed #53

Fix #53 - Social links params

---

_pages/es/experiments/test-pilot.md

New PR, as per @nukeador suggestion in https://github.com/mozilla/activate.mozilla.community/pull/61#issuecomment-251105336

Localización al Español

---

_pages/webcompat-sprint.md

Work done with @alex-mayorga and the web compat team during MozAloha.

Simplify the WebCompat outline.

---

locales/pt-BR/activities.xlf

Fix pt-BR file

---

_pages/activities.md
_pages/community-participation-guidelines.md

Initial Draft 
* still waiting on approval by @larissashaprio
* I updated the main activate page, but the link  to doesn't work (I am not sure why), however the redirect from experiment/community-participation-guidelines does work, so maybe I am just missing a file update.
Does this move to a dev/test server before production push?  How can stakeholders review before approval?  Thanks

CPG Activate Campaign - Draft

---

_pages/es/roadmap.md
_pages/fr/roadmap.md
_pages/pt/roadmap.md
_pages/roadmap.md

I didn't update the xliff yet, due to https://github.com/mozilla/activate.mozilla.community/issues/139#issuecomment-281153122

Add current roadmap + latest changes section (fixes #145)

---

_pages/activities.md
_pages/community-participation-guidelines.md

CPG Activate Campaign

---

_pages/participation.md

I think it makes sense this section remains participation (that is still the action!) but I adjusted the team name to Community Development.

Updated team title

---

_pages/es/webextensions.md

Little Changes to content under es' locale

---

_pages/webextensions.md

1. Added 's' to matters in last line. - Rest of the changes can be compared.

Little changes to the content

---

_pages/community-participation-guidelines.md
_pages/es/community-participation-guidelines.md
_pages/fr/community-participation-guidelines.md
_pages/pt/community-participation-guidelines.md

As stated in Telegram I find it kind of confusing what D&I stands for. So I added it in braces at the first occurence. I went on and added it for other languages as well.

Added hint on what D&I means to all languages.

---

_pages/es/webextensions.md
_pages/fr/webextensions.md
_pages/webextensions.md

Details how to tag submission with `mozactivate17`.

Updated submission process for webextensions activity

---

_pages/community-participation-guidelines.md

Removed a lot of texts, simplified
added telegram/twitter chat for Thursday.

Update to CPG Activate - Simplified & Added Telegram/Mozillians Chat

---

_pages/es/community-participation-guidelines.md

I updated the Spanish version of the Community Participation Guidelines.

Spanish l10n.

---

_pages/es/community-participation-guidelines.md

Fixed the correct translation of Mozillians
Minor changes, and correct hashtag.
Signed-off-by: Jose Suarez <Jozhee@live.com>

Minor changes to l10n-es

---

_pages/es/faq.md
_pages/faq.md
_pages/fr/faq.md

Updated all locales apart from PT, since that one is already localized.

Add specific section for swag to FAQ (fixes #127)

---

_sass/_layout.scss

Let's make the footer darker to increase the contrast

Increase footer contrast

---

_includes/page-languages.html

Uppercase for languages in footer

---

_sass/_base.scss
_sass/_layout.scss

Fix nav on md displays

---

_pages/es/participation.md
_pages/participation.md
_pages/pt/participation.md
_sass/_layout.scss

Make FAQ and Participation better readable with more space

---

_pages/es/roadmap.md
_pages/pt/roadmap.md
_pages/roadmap.md

Put Nightly in Q2 column in Roadmap

---

_data/l10n/pt.yml
_pages/pt/activities.md
_pages/pt/faq.md
_pages/pt/index.md
_pages/pt/techspeakers.md
_pages/pt/webextensions.md

Hello Activate team,
I have worked today **updating, improving and adding new translations**, are not complete yet, but we will work collaboratively among volunteers and then we'll send new translations ASAP.
**Some observations are important:**
- I not find any files to add translations of the activities (summary, type of activity, name and time) located in the home page and in the footer.
- Our language is derived from Portuguese from Portugal, but our Portuguese is Brazilian, so the correct one is use PT-BR. It is not good practice to use PT for Brazilian Portuguese, because our community in Portugal may want to translate this project in the future and they will want to use PT in the "lang".
- Finally, I believe that some updates are need in the FAQ page.
Cheers 👍 
Geraldo Barros

Improvement, updating and addition of new translations for PT-BR

---

_includes/jumbotron.html
_sass/_layout.scss

Center header text on frontpage

---

_pages/es/eventguide.md
_pages/eventguide.md
_pages/pt-BR/eventguide.md

Added the https://mzl.la/howwasit link in the get feedback section.

Added the feedback form link

---

_pages/es/webextensions.md

Updated line 118 to include telegram chat @addonschat.

Added @addonschat

---

_pages/webextensions.md

Added @addonschat to line 118.

Update Telegram groups

---

_pages/es/rust-hack.md
_pages/pt-BR/rust-hack.md
_pages/rust-hack.md

Fix to https://github.com/mozilla/activate.mozilla.community/issues/240
I have used the same [URL](https://www.rust-lang.org/en-US/other-installers.html) for all the three languages since the content written is in english.

rust-hack.md atlernate link update

---

_pages/impactform.md

@couci wants the link to be the same as the original form. Hence, now I'm changing it from /impactform to /howwasit

Change impact form link

---

_pages/pt-BR/webextensions.md

Break tutorials & other resources into two parts; add MDN tutorial and example WebExtensions.

Update tutorials & other resources

---

_pages/es/webextensions.md
_pages/id/webextensions.md
_pages/pt-BR/webextensions.md
_pages/webextensions.md

Looks like the UI is broken on add-ons activity page. Fixed it.

fixed the broken UI issue on add-ons activity page

---

_pages/faq.md

Only changed the string in EN, as both pt-BR and ES are translated.

Change goal in FAQ

---

_includes/index.md

Simple typo fix

---

_pages/es/webextensions.md

Updating name and terminology for extensions, per guidance here: https://wiki.mozilla.org/Add-ons/Terminology

Update terminology - Extensions activity es

---

_data/l10n/es.yml
_pages/es/webcompat-sprint.md

Add Spanish translation to webcompat-sprint
Add Spanish translation to es menu.

Add Spanish translation to Web Compat Sprint

---

_pages/webextensions.md

- New goals for WebExtension added
- New Metrics.
- New event flow is shared.

Webextension page modified

---

LICENSE
README.md
scripts/start.js
src/components/Activities/Nightly.js
src/components/Activities/RustHack.js
src/components/Activities/TechSpeakers.js
src/components/Activities/WebVRCamp.js
src/components/Activities/WebcompatSprint.js
src/components/NewsletterForm.js

Changed links to HTTPS when supported.
Closes #314

Update HTTP to HTTPS

---

public/locales/en-US/activate.ftl
src/components/Header.css
src/components/Header.js

Add links to community portal (fixes #372)
